GET http://localhost:5006

###

GET http://localhost:5006/autores 

###

GET http://localhost:5006/autores/2

###



POST http://localhost:5006/autores
Content-Type: application/json

{
    "Nome": "Jorge Amado",
    "Nacionalidade": "Brasileiro",
    "DataNascimento": "1912-08-10",
    "Livros": "Capitães da Areia, Gabriela, Cravo e Canela"
}